# Generated by Django 2.2.1 on 2019-06-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190605_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedetail',
            name='fine',
            field=models.IntegerField(default=0),
        ),
    ]
