# Generated by Django 2.2.1 on 2019-06-05 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190605_1249'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='issuedetail',
            name='issue_status',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='books.IssueStatus'),
            preserve_default=False,
        ),
    ]
