# Generated by Django 2.2.1 on 2019-06-05 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190605_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issuedetail',
            name='issue_status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='books.IssueStatus'),
        ),
        migrations.AlterField(
            model_name='issuedetail',
            name='issued_on',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='issuedetail',
            name='returned_on',
            field=models.DateField(blank=True),
        ),
    ]
